<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatform">
      <_Parameter1>linux</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Carina.Contracts/Carina.Contracts.csproj" />
  </ItemGroup>

</Project>
