version: '3'

tasks:
  up:
    cmd: docker compose up -d
  down:
    cmd: docker compose down
  stop:
    cmd: docker compose stop
  bash:
    cmd: docker compose exec app /bin/bash
  restore:
    cmd: docker compose exec app dotnet restore
  build:
    cmd: docker compose exec app dotnet build
  test:
    cmd: docker compose exec app dotnet test
  test:scale:
    cmd: docker compose exec app dotnet test --filter "Category=Scale" --logger "console;verbosity=detailed"
  format:
    cmd: docker compose exec app dotnet format
  lint:
    cmd: docker compose exec app dotnet format --verify-no-changes
  run:app:
    cmd: docker compose exec app dotnet run --project src/Carina.Api
  restart:driver:
    cmd: docker compose restart driver
  logs:driver:
    cmd: docker compose logs -f driver
  probe:driver:
    cmd: docker compose exec driver dotnet /driver/bin/Carina.Driver/debug/Carina.Driver.dll --probe
  migrate:
    cmd: docker compose exec app dotnet run --project src/Carina.Db -- --migrate
  psql:
    cmd: docker compose exec db psql -U carina -d carina
  image:
    cmd: docker build -t carina .
