<Project>

  <Import Project="$(MSBuildThisFileDirectory)../Directory.Build.props" />

  <PropertyGroup>
    <CarinaIsTestProject>$(MSBuildProjectName.EndsWith('.Tests'))</CarinaIsTestProject>
    <IsTestProject>$(CarinaIsTestProject)</IsTestProject>
  </PropertyGroup>

  <ItemGroup Condition="'$(CarinaIsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup Condition="'$(CarinaIsTestProject)' == 'true'">
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
