// <auto-generated />
using System;
using System.Collections.Generic;
using Carina.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carina.Db.Migrations;

[DbContext(typeof(CarinaDbContext))]
[Migration("20260819101642_StreamVisitTally")]
partial class StreamVisitTally
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.HasSequence("programme_revision");

        modelBuilder.Entity("Carina.Domain.Auth.AuthSession", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(43)
                    .HasColumnType("character varying(43)")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("DeviceLabel")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)")
                    .HasColumnName("device_label");

                b.Property<DateTime>("LastUsedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_used_at");

                b.Property<string>("Method")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("method");

                b.Property<DateTime?>("RevokedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("revoked_at");

                b.Property<string>("Subject")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)")
                    .HasColumnName("subject");

                b.HasKey("Id")
                    .HasName("pk_auth_session");

                b.HasIndex("LastUsedAt")
                    .HasDatabaseName("ix_auth_session_last_used_at");

                b.HasIndex("Subject")
                    .HasDatabaseName("ix_auth_session_subject");

                b.ToTable("auth_session", null, t =>
                    {
                        t.HasCheckConstraint("ck_auth_session_device_label", "device_label <> ''");

                        t.HasCheckConstraint("ck_auth_session_method", "method IN ('Local', 'Oidc')");

                        t.HasCheckConstraint("ck_auth_session_times", "last_used_at >= created_at AND (revoked_at IS NULL OR revoked_at >= created_at)");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Auth.LocalAccount", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTime>("PasswordChangedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("password_changed_at");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("password_hash");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("username");

                b.HasKey("Id")
                    .HasName("pk_local_account");

                b.ToTable("local_account", null, t =>
                    {
                        t.HasCheckConstraint("ck_local_account_single_row", "id = 1 AND username <> '' AND password_changed_at >= created_at");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Auth.OidcSettings", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer")
                    .HasColumnName("id");

                b.PrimitiveCollection<string[]>("AllowedGroups")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text[]")
                    .HasColumnName("allowed_groups")
                    .HasDefaultValueSql("'{}'");

                b.PrimitiveCollection<string[]>("AllowedHostedDomains")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasColumnType("text[]")
                    .HasColumnName("allowed_hosted_domains")
                    .HasDefaultValueSql("'{}'");

                b.Property<string>("ClientId")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("client_id");

                b.Property<string>("ClientSecret")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("client_secret");

                b.Property<string>("DiscoveryUrl")
                    .HasMaxLength(2048)
                    .HasColumnType("character varying(2048)")
                    .HasColumnName("discovery_url");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.HasKey("Id")
                    .HasName("pk_oidc_config");

                b.ToTable("oidc_config", null, t =>
                    {
                        t.HasCheckConstraint("ck_oidc_config_single_row", "id = 1");

                        t.HasCheckConstraint("ck_oidc_config_whole", "(discovery_url IS NULL AND client_id IS NULL AND client_secret IS NULL) OR (discovery_url IS NOT NULL AND client_id IS NOT NULL AND client_secret IS NOT NULL)");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Channels.BroadcastService", b =>
            {
                b.Property<int>("NetworkId")
                    .HasColumnType("integer")
                    .HasColumnName("network_id");

                b.Property<int>("ServiceId")
                    .HasColumnType("integer")
                    .HasColumnName("service_id");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("category");

                b.Property<DateTime>("DiscoveredAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("discovered_at");

                b.Property<DateTime>("LastSeenAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_seen_at");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<int?>("RemoteControlKeyId")
                    .HasColumnType("integer")
                    .HasColumnName("remote_control_key_id");

                b.HasKey("NetworkId", "ServiceId")
                    .HasName("pk_broadcast_service");

                b.HasIndex("LastSeenAt")
                    .HasDatabaseName("ix_broadcast_service_last_seen_at");

                b.ToTable("broadcast_service", null, t =>
                    {
                        t.HasCheckConstraint("ck_broadcast_service_category", "category IN ('Television', 'Radio', 'Data', 'OneSeg', 'Temporary', 'Other')");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Channels.CandidateChannel", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<int>("ConsecutiveFailures")
                    .HasColumnType("integer")
                    .HasColumnName("consecutive_failures");

                b.Property<DateTime>("DiscoveredAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("discovered_at");

                b.Property<bool>("IsSelected")
                    .HasColumnType("boolean")
                    .HasColumnName("is_selected");

                b.Property<DateTime>("LastSeenAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_seen_at");

                b.Property<DateTime?>("NeedsAttentionSince")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("needs_attention_since");

                b.Property<bool>("NeedsRevalidation")
                    .HasColumnType("boolean")
                    .HasColumnName("needs_revalidation");

                b.Property<int>("NetworkId")
                    .HasColumnType("integer")
                    .HasColumnName("network_id");

                b.Property<DateTime?>("NextAttemptAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("next_attempt_at");

                b.Property<int?>("ObservedStreamId")
                    .HasColumnType("integer")
                    .HasColumnName("observed_transport_stream_id");

                b.Property<string>("RotationState")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("rotation_state");

                b.Property<DateTime?>("SelectedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("selected_at");

                b.Property<string>("SelectionSource")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("selection_source");

                b.Property<int>("ServiceId")
                    .HasColumnType("integer")
                    .HasColumnName("service_id");

                b.ComplexProperty(typeof(Dictionary<string, object>), "LastMeasurement", "Carina.Domain.Channels.CandidateChannel.LastMeasurement#SignalMeasurement", b1 =>
                    {
                        b1.Property<int?>("CnrMilliDecibels")
                            .HasColumnType("integer")
                            .HasColumnName("cnr_milli_decibels");

                        b1.Property<bool>("Locked")
                            .HasColumnType("boolean")
                            .HasColumnName("locked");

                        b1.Property<DateTime>("MeasuredAt")
                            .HasColumnType("timestamp with time zone")
                            .HasColumnName("measured_at");

                        b1.Property<long?>("PostViterbiErrorBits")
                            .HasColumnType("bigint")
                            .HasColumnName("post_viterbi_error_bits");

                        b1.Property<long?>("PostViterbiTotalBits")
                            .HasColumnType("bigint")
                            .HasColumnName("post_viterbi_total_bits");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "SelectionMeasurement", "Carina.Domain.Channels.CandidateChannel.SelectionMeasurement#SignalMeasurement", b1 =>
                    {
                        b1.Property<int?>("CnrMilliDecibels")
                            .HasColumnType("integer")
                            .HasColumnName("selected_cnr_milli_decibels");

                        b1.Property<bool>("Locked")
                            .HasColumnType("boolean")
                            .HasColumnName("selected_locked");

                        b1.Property<DateTime>("MeasuredAt")
                            .HasColumnType("timestamp with time zone")
                            .HasColumnName("selected_measured_at");

                        b1.Property<long?>("PostViterbiErrorBits")
                            .HasColumnType("bigint")
                            .HasColumnName("selected_post_viterbi_error_bits");

                        b1.Property<long?>("PostViterbiTotalBits")
                            .HasColumnType("bigint")
                            .HasColumnName("selected_post_viterbi_total_bits");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Tuning", "Carina.Domain.Channels.CandidateChannel.Tuning#TuningParameters", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<int>("PhysicalChannel")
                            .HasColumnType("integer")
                            .HasColumnName("physical_channel");

                        b1.Property<string>("System")
                            .IsRequired()
                            .HasMaxLength(32)
                            .HasColumnType("character varying(32)")
                            .HasColumnName("tune_system");

                        b1.Property<int?>("TransportStreamId")
                            .HasColumnType("integer")
                            .HasColumnName("transport_stream_id");
                    });

                b.HasKey("Id")
                    .HasName("pk_candidate_channel");

                b.HasIndex("RotationState")
                    .HasDatabaseName("ix_candidate_channel_rotation_state");

                b.HasIndex("NetworkId", "ServiceId")
                    .IsUnique()
                    .HasDatabaseName("ux_candidate_channel_selected")
                    .HasFilter("is_selected");

                b.ToTable("candidate_channel", null, t =>
                    {
                        t.HasCheckConstraint("ck_candidate_channel_measurement_lock", "measured_at IS NULL OR locked OR cnr_milli_decibels IS NULL");

                        t.HasCheckConstraint("ck_candidate_channel_rotation", "consecutive_failures >= 0\nAND (rotation_state <> 'NeedsAttention'\n     OR (needs_attention_since IS NOT NULL AND next_attempt_at IS NULL))\nAND (rotation_state <> 'BackingOff' OR next_attempt_at IS NOT NULL)\nAND (rotation_state <> 'Active'\n     OR (next_attempt_at IS NULL AND needs_attention_since IS NULL))");

                        t.HasCheckConstraint("ck_candidate_channel_selection", "is_selected = (selection_source IS NOT NULL) AND is_selected = (selected_at IS NOT NULL)");

                        t.HasCheckConstraint("ck_candidate_channel_selection_measurement_lock", "selected_measured_at IS NULL OR selected_locked OR selected_cnr_milli_decibels IS NULL");

                        t.HasCheckConstraint("ck_candidate_channel_tuning", "(tune_system = 'IsdbT' AND physical_channel BETWEEN 13 AND 62 AND transport_stream_id IS NULL)\nOR (tune_system = 'IsdbSBs' AND physical_channel BETWEEN 1 AND 23 AND physical_channel % 2 = 1\n    AND physical_channel NOT IN (7, 17) AND transport_stream_id IS NOT NULL)\nOR (tune_system = 'IsdbSCs110' AND physical_channel BETWEEN 2 AND 24 AND physical_channel % 2 = 0\n    AND transport_stream_id IS NULL)");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Channels.SatelliteTransportStream", b =>
            {
                b.Property<int>("BsChannel")
                    .HasColumnType("integer")
                    .HasColumnName("bs_channel");

                b.Property<int>("RelativeStreamNumber")
                    .HasColumnType("integer")
                    .HasColumnName("relative_stream_number");

                b.Property<int>("TransportStreamId")
                    .HasColumnType("integer")
                    .HasColumnName("transport_stream_id");

                b.HasKey("BsChannel", "RelativeStreamNumber")
                    .HasName("pk_satellite_transport_stream");

                b.ToTable("satellite_transport_stream", null, t =>
                    {
                        t.HasCheckConstraint("ck_satellite_transport_stream_slot", "bs_channel BETWEEN 1 AND 23 AND bs_channel % 2 = 1 AND bs_channel NOT IN (7, 17)\nAND relative_stream_number BETWEEN 0 AND 7");
                    });

                b.HasData(
                    new
                    {
                        BsChannel = 1,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16400
                    },
                    new
                    {
                        BsChannel = 3,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16432
                    },
                    new
                    {
                        BsChannel = 5,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16464
                    },
                    new
                    {
                        BsChannel = 9,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16528
                    },
                    new
                    {
                        BsChannel = 11,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16560
                    },
                    new
                    {
                        BsChannel = 13,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16592
                    },
                    new
                    {
                        BsChannel = 15,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16624
                    },
                    new
                    {
                        BsChannel = 19,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16688
                    },
                    new
                    {
                        BsChannel = 21,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16720
                    },
                    new
                    {
                        BsChannel = 23,
                        RelativeStreamNumber = 0,
                        TransportStreamId = 16752
                    });
            });

        modelBuilder.Entity("Carina.Domain.Programmes.ArchivedProgramme", b =>
            {
                b.Property<int>("NetworkId")
                    .HasColumnType("integer")
                    .HasColumnName("network_id");

                b.Property<int>("ServiceId")
                    .HasColumnType("integer")
                    .HasColumnName("service_id");

                b.Property<int>("EventId")
                    .HasColumnType("integer")
                    .HasColumnName("event_id");

                b.Property<DateTime>("StartsAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_at");

                b.Property<DateTime>("ArchivedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("archived_at");

                b.Property<DateTime>("EndsAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_at");

                b.Property<string>("Genres")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("genres");

                b.Property<bool>("HasSubtitles")
                    .HasColumnType("boolean")
                    .HasColumnName("has_subtitles");

                b.Property<string>("Items")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("items");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("name");

                b.Property<string>("Summary")
                    .IsRequired()
                    .HasMaxLength(4096)
                    .HasColumnType("character varying(4096)")
                    .HasColumnName("summary");

                b.HasKey("NetworkId", "ServiceId", "EventId", "StartsAt")
                    .HasName("pk_archived_programme");

                b.HasIndex("EndsAt")
                    .HasDatabaseName("ix_archived_programme_end_at");

                b.ToTable("archived_programme", null, t =>
                    {
                        t.HasCheckConstraint("ck_archived_programme_runs_forward", "end_at > start_at");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Programmes.CollectionEpoch", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("integer")
                    .HasColumnName("id");

                b.Property<DateTime>("AdvancedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("advanced_at");

                b.Property<int>("Generation")
                    .HasColumnType("integer")
                    .HasColumnName("generation");

                b.HasKey("Id")
                    .HasName("pk_collection_epoch");

                b.ToTable("collection_epoch", null, t =>
                    {
                        t.HasCheckConstraint("ck_collection_epoch_single_row", "id = 1 AND generation >= 1");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Programmes.Programme", b =>
            {
                b.Property<int>("NetworkId")
                    .HasColumnType("integer")
                    .HasColumnName("network_id");

                b.Property<int>("ServiceId")
                    .HasColumnType("integer")
                    .HasColumnName("service_id");

                b.Property<int>("EventId")
                    .HasColumnType("integer")
                    .HasColumnName("event_id");

                b.Property<DateTime?>("EndsAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("end_at");

                b.Property<string>("Genres")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("genres");

                b.Property<bool>("HasSubtitles")
                    .HasColumnType("boolean")
                    .HasColumnName("has_subtitles");

                b.Property<bool>("IsShadow")
                    .HasColumnType("boolean")
                    .HasColumnName("is_shadow");

                b.Property<string>("Items")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("items");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("name");

                b.Property<string>("Related")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("related");

                b.Property<long>("Revision")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("revision")
                    .HasDefaultValueSql("nextval('programme_revision')");

                b.Property<string>("Source")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("source");

                b.Property<DateTime>("StartsAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("start_at");

                b.Property<string>("Summary")
                    .IsRequired()
                    .HasMaxLength(4096)
                    .HasColumnType("character varying(4096)")
                    .HasColumnName("summary");

                b.Property<int>("TransportStreamId")
                    .HasColumnType("integer")
                    .HasColumnName("transport_stream_id");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<string>("searchable")
                    .ValueGeneratedOnAddOrUpdate()
                    .HasColumnType("text")
                    .HasColumnName("searchable")
                    .HasComputedColumnSql("lower(name || ' ' || summary)", true);

                b.HasKey("NetworkId", "ServiceId", "EventId")
                    .HasName("pk_programme");

                b.HasIndex("Revision")
                    .IsUnique()
                    .HasDatabaseName("ix_programme_revision");

                b.HasIndex("StartsAt")
                    .HasDatabaseName("ix_programme_start_at");

                b.HasIndex("UpdatedAt")
                    .HasDatabaseName("ix_programme_updated_at");

                b.ToTable("programme", null, t =>
                    {
                        t.HasCheckConstraint("ck_programme_runs_forward", "end_at IS NULL OR end_at > start_at");

                        t.HasCheckConstraint("ck_programme_source", "source IN ('PresentFollowing', 'ScheduleBasic', 'ScheduleExtended')");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Programmes.StreamVisit", b =>
            {
                b.Property<int>("NetworkId")
                    .HasColumnType("integer")
                    .HasColumnName("network_id");

                b.Property<int>("TransportStreamId")
                    .HasColumnType("integer")
                    .HasColumnName("transport_stream_id");

                b.Property<int>("ConsecutiveIncomplete")
                    .HasColumnType("integer")
                    .HasColumnName("consecutive_incomplete");

                b.Property<DateTime>("LastAttemptedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_attempted_at");

                b.Property<DateTime?>("LastCompletedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("last_completed_at");

                b.Property<int>("LastDurationMilliseconds")
                    .HasColumnType("integer")
                    .HasColumnName("last_duration_milliseconds");

                b.Property<string>("Outcome")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("outcome");

                b.HasKey("NetworkId", "TransportStreamId")
                    .HasName("pk_stream_visit");

                b.HasIndex("LastCompletedAt")
                    .HasDatabaseName("ix_stream_visit_last_completed_at");

                b.ToTable("stream_visit", null, t =>
                    {
                        t.HasCheckConstraint("ck_stream_visit_completion", "last_completed_at IS NULL OR last_completed_at <= last_attempted_at");

                        t.HasCheckConstraint("ck_stream_visit_counts", "consecutive_incomplete >= 0 AND last_duration_milliseconds >= 0");

                        t.HasCheckConstraint("ck_stream_visit_outcome", "outcome IN ('Complete', 'BasicOnly', 'Incomplete', 'Interrupted', 'NoLock', 'NoBytes')");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Programmes.VisitTally", b =>
            {
                b.Property<int>("NetworkId")
                    .HasColumnType("integer")
                    .HasColumnName("network_id");

                b.Property<int>("TransportStreamId")
                    .HasColumnType("integer")
                    .HasColumnName("transport_stream_id");

                b.Property<int>("ServiceId")
                    .HasColumnType("integer")
                    .HasColumnName("service_id");

                b.Property<int>("TableId")
                    .HasColumnType("integer")
                    .HasColumnName("table_id");

                b.Property<int>("LastTableId")
                    .HasColumnType("integer")
                    .HasColumnName("last_table_id");

                b.Property<int>("SectionsDeclared")
                    .HasColumnType("integer")
                    .HasColumnName("sections_declared");

                b.Property<int>("SectionsHeard")
                    .HasColumnType("integer")
                    .HasColumnName("sections_heard");

                b.Property<int>("SegmentsDeclared")
                    .HasColumnType("integer")
                    .HasColumnName("segments_declared");

                b.Property<int>("SegmentsHeard")
                    .HasColumnType("integer")
                    .HasColumnName("segments_heard");

                b.Property<int>("VersionChanges")
                    .HasColumnType("integer")
                    .HasColumnName("version_changes");

                b.HasKey("NetworkId", "TransportStreamId", "ServiceId", "TableId")
                    .HasName("pk_stream_visit_tally");

                b.ToTable("stream_visit_tally", null, t =>
                    {
                        t.HasCheckConstraint("ck_stream_visit_tally_counts", "segments_declared >= segments_heard AND segments_heard >= 0 AND sections_declared >= 0 AND sections_heard >= 0 AND version_changes >= 0");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Scans.ScanRun", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("DriverInstanceId")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("driver_instance_id");

                b.Property<DateTime?>("FinishedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("finished_at");

                b.Property<string>("Reason")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("reason");

                b.Property<DateTime>("StartedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("started_at");

                b.Property<string>("State")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("state");

                b.HasKey("Id")
                    .HasName("pk_scan_run");

                b.HasIndex("StartedAt")
                    .HasDatabaseName("ix_scan_run_started_at");

                b.HasIndex("State")
                    .IsUnique()
                    .HasDatabaseName("ux_scan_run_running")
                    .HasFilter("state = 'Running'");

                b.ToTable("scan_run", null, t =>
                    {
                        t.HasCheckConstraint("ck_scan_run_finished", "(state = 'Running') = (finished_at IS NULL)");

                        t.HasCheckConstraint("ck_scan_run_reason", "state NOT IN ('Failed', 'Cancelled') OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");

                        t.HasCheckConstraint("ck_scan_run_state", "state IN ('Running', 'Completed', 'Failed', 'Cancelled', 'Interrupted')");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Scans.ScanRunAttempt", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("Detail")
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)")
                    .HasColumnName("detail");

                b.Property<DateTime>("FinishedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("finished_at");

                b.Property<int?>("ObservedTransportStreamId")
                    .HasColumnType("integer")
                    .HasColumnName("observed_transport_stream_id");

                b.Property<string>("Outcome")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("outcome");

                b.Property<Guid>("ScanRunId")
                    .HasColumnType("uuid")
                    .HasColumnName("scan_run_id");

                b.Property<DateTime>("StartedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("started_at");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Measurement", "Carina.Domain.Scans.ScanRunAttempt.Measurement#SignalMeasurement", b1 =>
                    {
                        b1.Property<int?>("CnrMilliDecibels")
                            .HasColumnType("integer")
                            .HasColumnName("cnr_milli_decibels");

                        b1.Property<bool>("Locked")
                            .HasColumnType("boolean")
                            .HasColumnName("locked");

                        b1.Property<DateTime>("MeasuredAt")
                            .HasColumnType("timestamp with time zone")
                            .HasColumnName("measured_at");

                        b1.Property<long?>("PostViterbiErrorBits")
                            .HasColumnType("bigint")
                            .HasColumnName("post_viterbi_error_bits");

                        b1.Property<long?>("PostViterbiTotalBits")
                            .HasColumnType("bigint")
                            .HasColumnName("post_viterbi_total_bits");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "Tuning", "Carina.Domain.Scans.ScanRunAttempt.Tuning#TuningParameters", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<int>("PhysicalChannel")
                            .HasColumnType("integer")
                            .HasColumnName("physical_channel");

                        b1.Property<string>("System")
                            .IsRequired()
                            .HasMaxLength(32)
                            .HasColumnType("character varying(32)")
                            .HasColumnName("tune_system");

                        b1.Property<int?>("TransportStreamId")
                            .HasColumnType("integer")
                            .HasColumnName("transport_stream_id");
                    });

                b.HasKey("Id")
                    .HasName("pk_scan_run_attempt");

                b.HasIndex("ScanRunId", "Outcome")
                    .HasDatabaseName("ix_scan_run_attempt_scan_run_id_outcome");

                b.ToTable("scan_run_attempt", null, t =>
                    {
                        t.HasCheckConstraint("ck_scan_run_attempt_measurement_lock", "measured_at IS NULL OR locked OR cnr_milli_decibels IS NULL");

                        t.HasCheckConstraint("ck_scan_run_attempt_outcome", "outcome IN ('Succeeded', 'NoLock', 'LockedWithoutData', 'IncompleteTables', 'UnexpectedStream')");

                        t.HasCheckConstraint("ck_scan_run_attempt_span", "finished_at >= started_at");

                        t.HasCheckConstraint("ck_scan_run_attempt_tuning", "(tune_system = 'IsdbT' AND physical_channel BETWEEN 13 AND 62 AND transport_stream_id IS NULL)\nOR (tune_system = 'IsdbSBs' AND physical_channel BETWEEN 1 AND 23 AND physical_channel % 2 = 1\n    AND physical_channel NOT IN (7, 17) AND transport_stream_id IS NOT NULL)\nOR (tune_system = 'IsdbSCs110' AND physical_channel BETWEEN 2 AND 24 AND physical_channel % 2 = 0\n    AND transport_stream_id IS NULL)");
                    });
            });

        modelBuilder.Entity("Carina.Domain.Channels.CandidateChannel", b =>
            {
                b.HasOne("Carina.Domain.Channels.BroadcastService", null)
                    .WithMany()
                    .HasForeignKey("NetworkId", "ServiceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_candidate_channel_broadcast_service_network_id_service_id");
            });

        modelBuilder.Entity("Carina.Domain.Programmes.VisitTally", b =>
            {
                b.HasOne("Carina.Domain.Programmes.StreamVisit", null)
                    .WithMany("Tally")
                    .HasForeignKey("NetworkId", "TransportStreamId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_stream_visit_tally_stream_visit_network_id_transport_stream");
            });

        modelBuilder.Entity("Carina.Domain.Scans.ScanRunAttempt", b =>
            {
                b.HasOne("Carina.Domain.Scans.ScanRun", null)
                    .WithMany()
                    .HasForeignKey("ScanRunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_scan_run_attempt_scan_run_scan_run_id");
            });

        modelBuilder.Entity("Carina.Domain.Programmes.StreamVisit", b =>
            {
                b.Navigation("Tally");
            });
#pragma warning restore 612, 618
    }
}
