// <auto-generated />
using System;
using System.Collections.Generic;
using Carina.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Carina.Db.Migrations
{
    [DbContext(typeof(CarinaDbContext))]
    partial class CarinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("programme_revision");

            modelBuilder.Entity("Carina.Domain.Auth.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_label");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("method");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_auth_session");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_auth_session_last_used_at");

                    b.HasIndex("Subject")
                        .HasDatabaseName("ix_auth_session_subject");

                    b.ToTable("auth_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_auth_session_device_label", "device_label <> ''");

                            t.HasCheckConstraint("ck_auth_session_method", "method IN ('Local', 'Oidc')");

                            t.HasCheckConstraint("ck_auth_session_times", "last_used_at >= created_at AND (revoked_at IS NULL OR revoked_at >= created_at)");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Auth.LocalAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_local_account");

                    b.ToTable("local_account", null, t =>
                        {
                            t.HasCheckConstraint("ck_local_account_single_row", "id = 1 AND username <> '' AND password_changed_at >= created_at");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Auth.OidcSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedGroups")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_groups")
                        .HasDefaultValueSql("'{}'");

                    b.PrimitiveCollection<string[]>("AllowedHostedDomains")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("allowed_hosted_domains")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("client_secret");

                    b.Property<string>("DiscoveryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("discovery_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_oidc_config");

                    b.ToTable("oidc_config", null, t =>
                        {
                            t.HasCheckConstraint("ck_oidc_config_single_row", "id = 1");

                            t.HasCheckConstraint("ck_oidc_config_whole", "(discovery_url IS NULL AND client_id IS NULL AND client_secret IS NULL) OR (discovery_url IS NOT NULL AND client_id IS NOT NULL AND client_secret IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Channels.BroadcastService", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int?>("RemoteControlKeyId")
                        .HasColumnType("integer")
                        .HasColumnName("remote_control_key_id");

                    b.HasKey("NetworkId", "ServiceId")
                        .HasName("pk_broadcast_service");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_broadcast_service_last_seen_at");

                    b.ToTable("broadcast_service", null, t =>
                        {
                            t.HasCheckConstraint("ck_broadcast_service_category", "category IN ('Television', 'Radio', 'Data', 'OneSeg', 'Temporary', 'Other')");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Channels.CandidateChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selected");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTime?>("NeedsAttentionSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("needs_attention_since");

                    b.Property<bool>("NeedsRevalidation")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_revalidation");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<int?>("ObservedStreamId")
                        .HasColumnType("integer")
                        .HasColumnName("observed_transport_stream_id");

                    b.Property<string>("RotationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rotation_state");

                    b.Property<DateTime?>("SelectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at");

                    b.Property<string>("SelectionSource")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("selection_source");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LastMeasurement", "Carina.Domain.Channels.CandidateChannel.LastMeasurement#SignalMeasurement", b1 =>
                        {
                            b1.Property<int?>("CnrMilliDecibels")
                                .HasColumnType("integer")
                                .HasColumnName("cnr_milli_decibels");

                            b1.Property<bool>("Locked")
                                .HasColumnType("boolean")
                                .HasColumnName("locked");

                            b1.Property<DateTime>("MeasuredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("measured_at");

                            b1.Property<long?>("PostViterbiErrorBits")
                                .HasColumnType("bigint")
                                .HasColumnName("post_viterbi_error_bits");

                            b1.Property<long?>("PostViterbiTotalBits")
                                .HasColumnType("bigint")
                                .HasColumnName("post_viterbi_total_bits");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SelectionMeasurement", "Carina.Domain.Channels.CandidateChannel.SelectionMeasurement#SignalMeasurement", b1 =>
                        {
                            b1.Property<int?>("CnrMilliDecibels")
                                .HasColumnType("integer")
                                .HasColumnName("selected_cnr_milli_decibels");

                            b1.Property<bool>("Locked")
                                .HasColumnType("boolean")
                                .HasColumnName("selected_locked");

                            b1.Property<DateTime>("MeasuredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("selected_measured_at");

                            b1.Property<long?>("PostViterbiErrorBits")
                                .HasColumnType("bigint")
                                .HasColumnName("selected_post_viterbi_error_bits");

                            b1.Property<long?>("PostViterbiTotalBits")
                                .HasColumnType("bigint")
                                .HasColumnName("selected_post_viterbi_total_bits");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tuning", "Carina.Domain.Channels.CandidateChannel.Tuning#TuningParameters", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("PhysicalChannel")
                                .HasColumnType("integer")
                                .HasColumnName("physical_channel");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("tune_system");

                            b1.Property<int?>("TransportStreamId")
                                .HasColumnType("integer")
                                .HasColumnName("transport_stream_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_candidate_channel");

                    b.HasIndex("RotationState")
                        .HasDatabaseName("ix_candidate_channel_rotation_state");

                    b.HasIndex("NetworkId", "ServiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_candidate_channel_selected")
                        .HasFilter("is_selected");

                    b.ToTable("candidate_channel", null, t =>
                        {
                            t.HasCheckConstraint("ck_candidate_channel_measurement_lock", "measured_at IS NULL OR locked OR cnr_milli_decibels IS NULL");

                            t.HasCheckConstraint("ck_candidate_channel_rotation", "consecutive_failures >= 0\nAND (rotation_state <> 'NeedsAttention'\n     OR (needs_attention_since IS NOT NULL AND next_attempt_at IS NULL))\nAND (rotation_state <> 'BackingOff' OR next_attempt_at IS NOT NULL)\nAND (rotation_state <> 'Active'\n     OR (next_attempt_at IS NULL AND needs_attention_since IS NULL))");

                            t.HasCheckConstraint("ck_candidate_channel_selection", "is_selected = (selection_source IS NOT NULL) AND is_selected = (selected_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_candidate_channel_selection_measurement_lock", "selected_measured_at IS NULL OR selected_locked OR selected_cnr_milli_decibels IS NULL");

                            t.HasCheckConstraint("ck_candidate_channel_tuning", "(tune_system = 'IsdbT' AND physical_channel BETWEEN 13 AND 62 AND transport_stream_id IS NULL)\nOR (tune_system = 'IsdbSBs' AND physical_channel BETWEEN 1 AND 23 AND physical_channel % 2 = 1\n    AND physical_channel NOT IN (7, 17) AND transport_stream_id IS NOT NULL)\nOR (tune_system = 'IsdbSCs110' AND physical_channel BETWEEN 2 AND 24 AND physical_channel % 2 = 0\n    AND transport_stream_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Channels.SatelliteTransportStream", b =>
                {
                    b.Property<int>("BsChannel")
                        .HasColumnType("integer")
                        .HasColumnName("bs_channel");

                    b.Property<int>("RelativeStreamNumber")
                        .HasColumnType("integer")
                        .HasColumnName("relative_stream_number");

                    b.Property<int>("TransportStreamId")
                        .HasColumnType("integer")
                        .HasColumnName("transport_stream_id");

                    b.HasKey("BsChannel", "RelativeStreamNumber")
                        .HasName("pk_satellite_transport_stream");

                    b.ToTable("satellite_transport_stream", null, t =>
                        {
                            t.HasCheckConstraint("ck_satellite_transport_stream_slot", "bs_channel BETWEEN 1 AND 23 AND bs_channel % 2 = 1 AND bs_channel NOT IN (7, 17)\nAND relative_stream_number BETWEEN 0 AND 7");
                        });

                    b.HasData(
                        new
                        {
                            BsChannel = 1,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16400
                        },
                        new
                        {
                            BsChannel = 3,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16432
                        },
                        new
                        {
                            BsChannel = 5,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16464
                        },
                        new
                        {
                            BsChannel = 9,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16528
                        },
                        new
                        {
                            BsChannel = 11,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16560
                        },
                        new
                        {
                            BsChannel = 13,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16592
                        },
                        new
                        {
                            BsChannel = 15,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16624
                        },
                        new
                        {
                            BsChannel = 19,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16688
                        },
                        new
                        {
                            BsChannel = 21,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16720
                        },
                        new
                        {
                            BsChannel = 23,
                            RelativeStreamNumber = 0,
                            TransportStreamId = 16752
                        });
                });

            modelBuilder.Entity("Carina.Domain.Programmes.ArchivedProgramme", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_subtitles");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("summary");

                    b.PrimitiveCollection<int[]>("genre_kinds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer[]")
                        .HasColumnName("genre_kinds")
                        .HasComputedColumnSql("string_to_array(nullif(translate(jsonb_path_query_array(genres, '$[*].kind')::text, '[] ', ''), ''), ',')::integer[]", true);

                    b.Property<string>("searchable")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("searchable")
                        .HasComputedColumnSql("lower(pg_catalog.normalize(name || ' ' || summary, 'NFKC'))", true);

                    b.HasKey("NetworkId", "ServiceId", "EventId", "StartsAt")
                        .HasName("pk_archived_programme");

                    b.HasIndex("EndsAt")
                        .HasDatabaseName("ix_archived_programme_end_at");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_archived_programme_start_at");

                    b.ToTable("archived_programme", null, t =>
                        {
                            t.HasCheckConstraint("ck_archived_programme_runs_forward", "end_at > start_at");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Programmes.CollectionEpoch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("AdvancedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("advanced_at");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.HasKey("Id")
                        .HasName("pk_collection_epoch");

                    b.ToTable("collection_epoch", null, t =>
                        {
                            t.HasCheckConstraint("ck_collection_epoch_single_row", "id = 1 AND generation >= 1");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Programmes.Programme", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_subtitles");

                    b.Property<bool>("IsShadow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shadow");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<string>("Related")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("related");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("revision")
                        .HasDefaultValueSql("nextval('programme_revision')");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("summary");

                    b.Property<int>("TransportStreamId")
                        .HasColumnType("integer")
                        .HasColumnName("transport_stream_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<int[]>("genre_kinds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer[]")
                        .HasColumnName("genre_kinds")
                        .HasComputedColumnSql("string_to_array(nullif(translate(jsonb_path_query_array(genres, '$[*].kind')::text, '[] ', ''), ''), ',')::integer[]", true);

                    b.Property<string>("searchable")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("searchable")
                        .HasComputedColumnSql("lower(pg_catalog.normalize(name || ' ' || summary, 'NFKC'))", true);

                    b.HasKey("NetworkId", "ServiceId", "EventId")
                        .HasName("pk_programme");

                    b.HasIndex("Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_programme_revision");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_programme_start_at");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_programme_updated_at");

                    b.ToTable("programme", null, t =>
                        {
                            t.HasCheckConstraint("ck_programme_runs_forward", "end_at IS NULL OR end_at > start_at");

                            t.HasCheckConstraint("ck_programme_source", "source IN ('PresentFollowing', 'ScheduleBasic', 'ScheduleExtended')");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Programmes.ProgrammeMatch", b =>
                {
                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.Property<bool>("HasSubtitles")
                        .HasColumnType("boolean")
                        .HasColumnName("has_subtitles");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsShadow")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shadow");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<string>("Related")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("related");

                    b.Property<long?>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.PrimitiveCollection<int[]>("genre_kinds")
                        .HasColumnType("integer[]")
                        .HasColumnName("genre_kinds");

                    b.Property<string>("searchable")
                        .HasColumnType("text")
                        .HasColumnName("searchable");

                    b.ToTable((string)null);

                    b.ToSqlQuery("SELECT\n    network_id,\n    service_id,\n    event_id,\n    start_at,\n    end_at,\n    name,\n    summary,\n    is_shadow,\n    has_subtitles,\n    source,\n    revision,\n    genres,\n    items,\n    related,\n    searchable,\n    genre_kinds,\n    false AS is_archived\nFROM programme\nUNION ALL\nSELECT\n    kept.network_id,\n    kept.service_id,\n    kept.event_id,\n    kept.start_at,\n    kept.end_at,\n    kept.name,\n    kept.summary,\n    false,\n    kept.has_subtitles,\n    NULL::character varying(32),\n    NULL::bigint,\n    kept.genres,\n    kept.items,\n    '[]'::jsonb,\n    kept.searchable,\n    kept.genre_kinds,\n    true\nFROM archived_programme AS kept\nWHERE NOT EXISTS (\n    SELECT 1\n    FROM programme AS held\n    WHERE held.network_id = kept.network_id\n      AND held.service_id = kept.service_id\n      AND held.event_id = kept.event_id\n      AND held.start_at = kept.start_at)");
                });

            modelBuilder.Entity("Carina.Domain.Programmes.StreamVisit", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("TransportStreamId")
                        .HasColumnType("integer")
                        .HasColumnName("transport_stream_id");

                    b.Property<int>("ConsecutiveIncomplete")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_incomplete");

                    b.Property<DateTime>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at");

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_completed_at");

                    b.Property<int>("LastDurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("last_duration_milliseconds");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.HasKey("NetworkId", "TransportStreamId")
                        .HasName("pk_stream_visit");

                    b.HasIndex("LastCompletedAt")
                        .HasDatabaseName("ix_stream_visit_last_completed_at");

                    b.ToTable("stream_visit", null, t =>
                        {
                            t.HasCheckConstraint("ck_stream_visit_completion", "last_completed_at IS NULL OR last_completed_at <= last_attempted_at");

                            t.HasCheckConstraint("ck_stream_visit_counts", "consecutive_incomplete >= 0 AND last_duration_milliseconds >= 0");

                            t.HasCheckConstraint("ck_stream_visit_outcome", "outcome IN ('Complete', 'BasicOnly', 'Incomplete', 'Interrupted', 'NoLock', 'NoBytes')");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Programmes.VisitTally", b =>
                {
                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("TransportStreamId")
                        .HasColumnType("integer")
                        .HasColumnName("transport_stream_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<int>("TableId")
                        .HasColumnType("integer")
                        .HasColumnName("table_id");

                    b.Property<int>("LastTableId")
                        .HasColumnType("integer")
                        .HasColumnName("last_table_id");

                    b.Property<int>("SectionsDeclared")
                        .HasColumnType("integer")
                        .HasColumnName("sections_declared");

                    b.Property<int>("SectionsHeard")
                        .HasColumnType("integer")
                        .HasColumnName("sections_heard");

                    b.Property<int>("SegmentsDeclared")
                        .HasColumnType("integer")
                        .HasColumnName("segments_declared");

                    b.Property<int>("SegmentsHeard")
                        .HasColumnType("integer")
                        .HasColumnName("segments_heard");

                    b.Property<int>("VersionChanges")
                        .HasColumnType("integer")
                        .HasColumnName("version_changes");

                    b.HasKey("NetworkId", "TransportStreamId", "ServiceId", "TableId")
                        .HasName("pk_stream_visit_tally");

                    b.ToTable("stream_visit_tally", null, t =>
                        {
                            t.HasCheckConstraint("ck_stream_visit_tally_counts", "segments_declared >= segments_heard AND segments_heard >= 0 AND sections_declared >= 0 AND sections_heard >= 0 AND version_changes >= 0");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Recordings.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AbortedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aborted_at");

                    b.Property<string>("BroadcastGroupKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("broadcast_group_key");

                    b.Property<string>("BroadcastGroupRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("broadcast_group_role");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<long>("EovfCount")
                        .HasColumnType("bigint")
                        .HasColumnName("eovf_count");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ExpectedWindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_window_end");

                    b.Property<DateTime>("ExpectedWindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_window_start");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long?>("FileSizeObserved")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_observed");

                    b.Property<string>("Interruptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interruptions");

                    b.Property<DateTime?>("MeasuredUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_updated_at");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<DateTime?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Outcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recording_outcome");

                    b.Property<string>("OutcomeDetail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("outcome_detail");

                    b.Property<string>("OutputRoot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("output_root");

                    b.Property<DateTime>("ProgrammeStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("programme_start_at");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<int>("ResumeCount")
                        .HasColumnType("integer")
                        .HasColumnName("resume_count");

                    b.Property<long?>("ScrambledPackets")
                        .HasColumnType("bigint")
                        .HasColumnName("scrambled_packets");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("SnapshotExtended")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("snapshot_extended");

                    b.Property<string>("SnapshotGenres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_genres");

                    b.Property<string>("SnapshotName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("snapshot_name");

                    b.Property<string>("SnapshotSummary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("snapshot_summary");

                    b.Property<DateTime>("StartedAtActual")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_actual");

                    b.Property<DateTime?>("StoppedAtActual")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at_actual");

                    b.Property<long>("WrittenDurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("written_duration_ms");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Counters", "Carina.Domain.Recordings.Recording.Counters#DropCounters", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long?>("Dropped")
                                .HasColumnType("bigint")
                                .HasColumnName("cc_dropped_packets");

                            b1.Property<bool>("Measured")
                                .HasColumnType("boolean")
                                .HasColumnName("cc_measured");

                            b1.Property<long?>("Total")
                                .HasColumnType("bigint")
                                .HasColumnName("cc_total_packets");
                        });

                    b.HasKey("Id")
                        .HasName("pk_recording");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_recording_reservation")
                        .HasFilter("reservation_id IS NOT NULL");

                    b.HasIndex("StartedAtActual")
                        .HasDatabaseName("ix_recording_in_flight")
                        .HasFilter("recording_outcome IS NULL");

                    b.HasIndex("Outcome", "StoppedAtActual")
                        .HasDatabaseName("ix_recording_settled");

                    b.ToTable("recording", null, t =>
                        {
                            t.HasCheckConstraint("ck_recording_broadcast_group", "broadcast_group_role IN ('Standalone', 'MovementPrimary', 'MovementSuppressed', 'RelaySegment')\nAND (broadcast_group_role = 'Standalone' OR broadcast_group_key IS NOT NULL)");

                            t.HasCheckConstraint("ck_recording_complete_was_asked_for", "recording_outcome IS DISTINCT FROM 'Complete' OR aborted_at IS NOT NULL");

                            t.HasCheckConstraint("ck_recording_counts", "written_duration_ms >= 0\nAND resume_count >= 0\nAND eovf_count >= 0\nAND (file_size_observed IS NULL OR file_size_observed >= 0)\nAND (scrambled_packets IS NULL OR scrambled_packets >= 0)");

                            t.HasCheckConstraint("ck_recording_empty_file_failed", "recording_outcome IS NULL OR file_size_observed <> 0 OR recording_outcome = 'Failed'");

                            t.HasCheckConstraint("ck_recording_file_name", "btrim(file_name) = file_name\nAND length(file_name) > 0\nAND file_name <> '.'\nAND strpos(file_name, '/') = 0\nAND strpos(file_name, chr(92)) = 0\nAND strpos(file_name, '..') = 0");

                            t.HasCheckConstraint("ck_recording_measurement", "(cc_measured\n    OR (cc_dropped_packets IS NULL AND cc_total_packets IS NULL))\nAND (NOT cc_measured\n    OR (cc_dropped_packets IS NOT NULL\n        AND cc_total_packets IS NOT NULL\n        AND cc_dropped_packets <= cc_total_packets\n        AND measured_updated_at IS NOT NULL))");

                            t.HasCheckConstraint("ck_recording_observation", "(file_size_observed IS NULL) = (observed_at IS NULL)");

                            t.HasCheckConstraint("ck_recording_outcome", "(recording_outcome IS NULL OR recording_outcome IN ('Complete', 'Truncated', 'Failed'))\nAND (recording_outcome IS NULL OR stopped_at_actual IS NOT NULL)\nAND (recording_outcome IS NULL OR file_size_observed IS NOT NULL)");

                            t.HasCheckConstraint("ck_recording_outcome_detail", "recording_outcome IS NULL\nOR recording_outcome = 'Complete'\nOR jsonb_array_length(outcome_detail) > 0");

                            t.HasCheckConstraint("ck_recording_window", "expected_window_end > expected_window_start");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Reservations.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("BroadcastGroupKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("broadcast_group_key");

                    b.Property<string>("BroadcastGroupRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("broadcast_group_role");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<bool>("EndAtConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("end_at_confirmed");

                    b.Property<bool>("EpgDiverged")
                        .HasColumnType("boolean")
                        .HasColumnName("epg_diverged");

                    b.Property<string>("EpgDivergences")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("epg_diverged_detail");

                    b.Property<bool>("EpgMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("epg_missing");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<int>("MarginAfter")
                        .HasColumnType("integer")
                        .HasColumnName("margin_after");

                    b.Property<int>("MarginBefore")
                        .HasColumnType("integer")
                        .HasColumnName("margin_before");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("ProgrammeStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("programme_start_at");

                    b.Property<string>("RecordingOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recording_outcome");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("SnapshotExtended")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("snapshot_extended");

                    b.Property<string>("SnapshotGenres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_genres");

                    b.Property<string>("SnapshotName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("snapshot_name");

                    b.Property<string>("SnapshotSummary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("snapshot_summary");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("composite_state")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("composite_state")
                        .HasComputedColumnSql("CASE\n    WHEN recording_outcome IS NOT NULL THEN recording_outcome\n    WHEN started_at IS NOT NULL THEN 'Recording'\n    ELSE state\nEND", true);

                    b.HasKey("Id")
                        .HasName("pk_reservation");

                    b.HasIndex("BroadcastGroupKey")
                        .HasDatabaseName("ix_reservation_broadcast_group");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_reservation_rule_id");

                    b.HasIndex("StartAt")
                        .HasDatabaseName("ix_reservation_claimable")
                        .HasFilter("started_at IS NULL AND state = 'Scheduled'");

                    b.HasIndex("StartAt", "EndAt")
                        .HasDatabaseName("ix_reservation_window")
                        .HasFilter("state IN ('Scheduled', 'Conflict')");

                    b.HasIndex("NetworkId", "ServiceId", "EventId", "ProgrammeStartsAt")
                        .IsUnique()
                        .HasDatabaseName("ux_reservation_programme");

                    b.ToTable("reservation", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservation_broadcast_group", "broadcast_group_role IN ('Standalone', 'MovementPrimary', 'MovementSuppressed', 'RelaySegment')\nAND (broadcast_group_role = 'Standalone' OR broadcast_group_key IS NOT NULL)");

                            t.HasCheckConstraint("ck_reservation_divergence", "epg_diverged = (jsonb_array_length(epg_diverged_detail) > 0)\nAND (acknowledged_at IS NULL OR epg_diverged OR epg_missing)");

                            t.HasCheckConstraint("ck_reservation_margins", "margin_before BETWEEN 0 AND 3600 AND margin_after BETWEEN 0 AND 3600");

                            t.HasCheckConstraint("ck_reservation_priority", "priority BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_reservation_recording_outcome", "recording_outcome IS NULL\nOR (recording_outcome IN ('Complete', 'Truncated', 'Failed') AND started_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_reservation_state", "state IN ('Scheduled', 'Conflict', 'Cancelled', 'Missed')");

                            t.HasCheckConstraint("ck_reservation_window", "end_at > start_at");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Reservations.ReservationOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EffectiveEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_end_at");

                    b.Property<DateTime>("EffectiveStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_start_at");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("NetworkId")
                        .HasColumnType("integer")
                        .HasColumnName("network_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("ProgrammeStartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("programme_start_at");

                    b.Property<string>("RecordedInstead")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recorded_instead");

                    b.Property<string>("RecordingOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recording_outcome");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer")
                        .HasColumnName("service_id");

                    b.Property<string>("SnapshotName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("snapshot_name");

                    b.Property<string>("TuneFailure")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tune_failure");

                    b.HasKey("Id")
                        .HasName("pk_reservation_outcome");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_reservation_outcome_occurred_at");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_reservation_outcome_reservation");

                    b.ToTable("reservation_outcome", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservation_outcome_kind", "kind IN ('Competing', 'Missed', 'TuneFailure', 'RecordingFailure')");

                            t.HasCheckConstraint("ck_reservation_outcome_recorded_instead", "kind = 'Competing' OR jsonb_array_length(recorded_instead) = 0");

                            t.HasCheckConstraint("ck_reservation_outcome_recording_outcome", "(recording_outcome IS NULL OR recording_outcome IN ('Complete', 'Truncated', 'Failed'))\nAND (kind <> 'RecordingFailure' OR recording_outcome IS NOT NULL)");

                            t.HasCheckConstraint("ck_reservation_outcome_tune_failure", "(tune_failure IS NULL\n OR tune_failure IN ('NoLock', 'NoData', 'IncompletePsi', 'StreamMismatch'))\nAND (kind <> 'TuneFailure' OR tune_failure IS NOT NULL)");

                            t.HasCheckConstraint("ck_reservation_outcome_window", "effective_end_at > effective_start_at");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Rules.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("MarginAfter")
                        .HasColumnType("integer")
                        .HasColumnName("margin_after");

                    b.Property<int>("MarginBefore")
                        .HasColumnType("integer")
                        .HasColumnName("margin_before");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("query");

                    b.HasKey("Id")
                        .HasName("pk_rule");

                    b.HasIndex("Priority", "CreatedAt", "Id")
                        .IsDescending(true, false, false)
                        .HasDatabaseName("ix_rule_precedence")
                        .HasFilter("enabled");

                    b.ToTable("rule", null, t =>
                        {
                            t.HasCheckConstraint("ck_rule_margins", "margin_before BETWEEN 0 AND 3600 AND margin_after BETWEEN 0 AND 3600");

                            t.HasCheckConstraint("ck_rule_priority", "priority BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_rule_query", "length(btrim(query)) > 0");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Scans.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DriverInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("driver_instance_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_scan_run");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_scan_run_started_at");

                    b.HasIndex("State")
                        .IsUnique()
                        .HasDatabaseName("ux_scan_run_running")
                        .HasFilter("state = 'Running'");

                    b.ToTable("scan_run", null, t =>
                        {
                            t.HasCheckConstraint("ck_scan_run_finished", "(state = 'Running') = (finished_at IS NULL)");

                            t.HasCheckConstraint("ck_scan_run_reason", "state NOT IN ('Failed', 'Cancelled') OR (reason IS NOT NULL AND length(btrim(reason)) > 0)");

                            t.HasCheckConstraint("ck_scan_run_state", "state IN ('Running', 'Completed', 'Failed', 'Cancelled', 'Interrupted')");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Scans.ScanRunAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("detail");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int?>("ObservedTransportStreamId")
                        .HasColumnType("integer")
                        .HasColumnName("observed_transport_stream_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_run_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Measurement", "Carina.Domain.Scans.ScanRunAttempt.Measurement#SignalMeasurement", b1 =>
                        {
                            b1.Property<int?>("CnrMilliDecibels")
                                .HasColumnType("integer")
                                .HasColumnName("cnr_milli_decibels");

                            b1.Property<bool>("Locked")
                                .HasColumnType("boolean")
                                .HasColumnName("locked");

                            b1.Property<DateTime>("MeasuredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("measured_at");

                            b1.Property<long?>("PostViterbiErrorBits")
                                .HasColumnType("bigint")
                                .HasColumnName("post_viterbi_error_bits");

                            b1.Property<long?>("PostViterbiTotalBits")
                                .HasColumnType("bigint")
                                .HasColumnName("post_viterbi_total_bits");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tuning", "Carina.Domain.Scans.ScanRunAttempt.Tuning#TuningParameters", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("PhysicalChannel")
                                .HasColumnType("integer")
                                .HasColumnName("physical_channel");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("tune_system");

                            b1.Property<int?>("TransportStreamId")
                                .HasColumnType("integer")
                                .HasColumnName("transport_stream_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_scan_run_attempt");

                    b.HasIndex("ScanRunId", "Outcome")
                        .HasDatabaseName("ix_scan_run_attempt_scan_run_id_outcome");

                    b.ToTable("scan_run_attempt", null, t =>
                        {
                            t.HasCheckConstraint("ck_scan_run_attempt_measurement_lock", "measured_at IS NULL OR locked OR cnr_milli_decibels IS NULL");

                            t.HasCheckConstraint("ck_scan_run_attempt_outcome", "outcome IN ('Succeeded', 'NoLock', 'LockedWithoutData', 'IncompleteTables', 'UnexpectedStream')");

                            t.HasCheckConstraint("ck_scan_run_attempt_span", "finished_at >= started_at");

                            t.HasCheckConstraint("ck_scan_run_attempt_tuning", "(tune_system = 'IsdbT' AND physical_channel BETWEEN 13 AND 62 AND transport_stream_id IS NULL)\nOR (tune_system = 'IsdbSBs' AND physical_channel BETWEEN 1 AND 23 AND physical_channel % 2 = 1\n    AND physical_channel NOT IN (7, 17) AND transport_stream_id IS NOT NULL)\nOR (tune_system = 'IsdbSCs110' AND physical_channel BETWEEN 2 AND 24 AND physical_channel % 2 = 0\n    AND transport_stream_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Carina.Domain.Channels.CandidateChannel", b =>
                {
                    b.HasOne("Carina.Domain.Channels.BroadcastService", null)
                        .WithMany()
                        .HasForeignKey("NetworkId", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_channel_broadcast_service_network_id_service_id");
                });

            modelBuilder.Entity("Carina.Domain.Programmes.VisitTally", b =>
                {
                    b.HasOne("Carina.Domain.Programmes.StreamVisit", null)
                        .WithMany("Tally")
                        .HasForeignKey("NetworkId", "TransportStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stream_visit_tally_stream_visit_network_id_transport_stream");
                });

            modelBuilder.Entity("Carina.Domain.Reservations.Reservation", b =>
                {
                    b.HasOne("Carina.Domain.Rules.Rule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reservation_rule_rule_id");
                });

            modelBuilder.Entity("Carina.Domain.Scans.ScanRunAttempt", b =>
                {
                    b.HasOne("Carina.Domain.Scans.ScanRun", null)
                        .WithMany()
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scan_run_attempt_scan_run_scan_run_id");
                });

            modelBuilder.Entity("Carina.Domain.Programmes.StreamVisit", b =>
                {
                    b.Navigation("Tally");
                });
#pragma warning restore 612, 618
        }
    }
}
