<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../Carina.Domain/Carina.Domain.csproj" />
    <ProjectReference Include="../Carina.Infrastructure/Carina.Infrastructure.csproj" />
    <ProjectReference Include="../Carina.Contracts/Carina.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

</Project>
