<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Carina.Broadcast/Carina.Broadcast.csproj" />
    <ProjectReference Include="../Carina.BroadcastTestSupport/Carina.BroadcastTestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Text/Broadcasts/eit-text-samples.tsv" />
    <EmbeddedResource Include="Tables/Broadcasts/eit-sections.bin" />
  </ItemGroup>

</Project>
