<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Carina.Infrastructure/Carina.Infrastructure.csproj" />
    <ProjectReference Include="../Carina.TestSupport/Carina.TestSupport.csproj" />
    <ProjectReference Include="../Carina.BroadcastTestSupport/Carina.BroadcastTestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Streaming/Probes/*.txt" />
  </ItemGroup>

</Project>
